### ISSUE TITLE
Adding duplicate compared repo on refresh

### ISSUE THREAD

**Issue by gabe-heim** [chaoss/augur#179] opened 2018-09-30 17:50 UTC
If you have a compared repo and you hit refresh on a page, each compared repo duplicates itself in the compared repo array and  an extra "&comparedTo[]=owner+repo" will be added to the query string with the same repo.

**Comment by ccarterlandis** [comment] 2018-10-25 20:18
Duplicate of [this](https://github.com/chaoss/augur/issues/186) issue. Closing this one, as the other one is in the proper format. Please use the other one linked above.

**Closed by ccarterlandis** 2018-10-25 20:18 UTC
Labels: duplicate
