### ISSUE TITLE
augur run throws error: command not found

### ISSUE THREAD

**Issue by Adarsh-NP** [chaoss/augur#601] opened 2020-03-11 20:01 UTC
**Describe the bug:**
after installing augur in my system which is ubuntu 19.10, first of all I get the warning 
![augurinstallfailed](https://user-images.githubusercontent.com/54997561/76458550-b785d380-6400-11ea-81ec-abf54e7640c3.png)

after that when I try to run augur using the command augur run I get this error 
![augurrun](https://user-images.githubusercontent.com/54997561/76458805-1c412e00-6401-11ea-904a-634424b15f9a.png)

Kindly help

**Comment by ccarterlandis** [comment] 2020-03-12 00:25
Hi @Adarsh-NP, can you share your `logs/backend.log` file? That should have more detail about what went wrong. That `Clock skew detected` error also seems weird...I've never seen that before. Hopefully the log files will provide some more clues!

**Comment by Adarsh-NP** [comment] 2020-03-12 07:20
@ccarterlandis  here are the backend-install.err and backend-install.log files

[backend-install.log](https://github.com/chaoss/augur/files/4322777/backend-install.log)


[backend-install.txt](https://github.com/chaoss/augur/files/4322795/backend-install.txt)

**Comment by ccarterlandis** [comment] 2020-03-12 23:13
@Adarsh-NP based on the output of `backend-install.log`, it looks to me like you're on the `master` branch. That branch is pretty outdated; I suggest checking out the `dev` branch locally, as I've cleaned up a lot of the problems with the installation process (and many others) there. 

After you've switched to `dev`, I recommend running `make clean`, and then running `make install` to make sure all the old build files get removed. If that doesn't work, you could try recreating your virtual environment. That `ModuleNotFound: _ctypes` error is interesting to me though. Are you using Ubuntu?

**Comment by Adarsh-NP** [comment] 2020-03-13 07:54
Yes, I am using Ubuntu 19.10

**Comment by ccarterlandis** [comment] 2020-03-16 16:06
Okay, we support Ubuntu 16.04 LTS and later (the latest I've personally tested is 18.04 LTS, but it stands to reason 19.10 should work as well). Have you been able to run the commands on the `dev` branch, and do you see the same output?

**Comment by Adarsh-NP** [comment] 2020-03-16 16:12
Yes,
On dev branch make commands are running but augur run still throws errors
and not running.

**Comment by ccarterlandis** [comment] 2020-03-16 16:14
Hmmm, okay. Are the logs any different, and if so could you share them again? 😁

**Comment by Adarsh-NP** [comment] 2020-03-16 16:15
Yeah sure
Just a minute

**Comment by Adarsh-NP** [comment] 2020-03-16 16:29
attaching backend-install.err, backend-install.log and backend.log 


[backend-install.log](https://github.com/chaoss/augur/files/4339161/backend-install.log)
[backend.log](https://github.com/chaoss/augur/files/4339164/backend.log)

[backend-install.txt](https://github.com/chaoss/augur/files/4339182/backend-install.txt)

Also this time there were more files than the ones after previous installation,  is it due to reinstallation, but that should have overridden the previous installation right?

Thanks in advance.

**Comment by ccarterlandis** [comment] 2020-03-16 17:32
Seems there was an error downloading the `urllib3` package:
```
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```
To be honest, I've never seen this error before. My first guess is that it's getting timed out because it's taking too long to download for some reason; can you think of anything that could be causing a slowdown like a VPN, proxy, or just poor internet connection? You could try setting the timeout to be higher than the default to see if that fixes anything (I will leave the details of doing that to you 😉 )

**Comment by NodiraIbrogimova** [comment] 2020-03-16 20:28
I'm getting error while I run `augur run` as well. 
As written [here,](https://oss-augur.readthedocs.io/en/dev/getting-started/available-commands/make-commands.html) I tried to run frontend and backend separately. 
`make frontend` throws:
`make: Nothing to be done for frontend`
And the documentation link in `make frontend` section isn't working. 
I was able to start frontend with `npm run start` (or just prompting from `package.lock`) on localhost, but for backend, I can't find any way to run without error.
Can you please help @ccarterlandis ?

**Comment by NodiraIbrogimova** [comment] 2020-03-17 04:11
@Adarsh-NP were you able to fix the error? If yes, can you please share with your solution?

**Comment by Adarsh-NP** [comment] 2020-03-17 04:18
No I still haven't been able to, I'll do it now, last few days went in
travelling to hometown because university decided to send students home in
the view of COVID-19.

But did you try switching to the Dev branch and run the command make clean
and then make install. See if it fixes the issue. More detailed information
is given in this thread above by Carter, refer to that in case of any
issues. Also if you run into new issues kindly share in this thread so that
we could help each other if need be.

Regards

**Comment by Adarsh-NP** [comment] 2020-03-17 05:47
Hello @NodiraIbrogimova , yeah, so I deleted the cloned repo, cloned it again and switched to dev branch immediately on the first run and ran make clean after that make install and it is working perfectly fine ie augur run now runs. 
Thanks @ccarterlandis  for helping me throughout and I hope this helps you @NodiraIbrogimova.

**Comment by Adarsh-NP** [comment] 2020-03-17 05:48
Also, @ccarterlandis should I close this issue, since it seems to be resolved as of now.

**Comment by NodiraIbrogimova** [comment] 2020-03-17 19:24
Dear @alexcourouble, thank you for providing the information. I'll try this suggestion and will let you guys know here

**Comment by NodiraIbrogimova** [comment] 2020-03-17 23:41
Repeating doing the installation process from the beginning. Recent two tries for:

1. deleting repo from development environment
2. checkout to dev branch
3. make clean
4. make install 
didn't work :/
I think maybe I'm choosing the wrong options and that might be throwing error.
For example, one question is about the option in screenshot below. Which options should I choose? What does this do? Clone remote repository? I see `facade_worker` in `workers` directory in `augur` project. I'm a bit confused. Help me someone please, blowing my brain with installation failure for several days already :D 
<img width="647" alt="Screen Shot 2020-03-18 at 4 34 01 AM" src="https://user-images.githubusercontent.com/11291840/76911277-46e42880-68d2-11ea-941f-33830b7e899d.png">

@Adarsh-NP maybe can you share with your experience with installation steps, please?

**Comment by Adarsh-NP** [comment] 2020-03-18 03:40
Hello @NodiraIbrogimova,  I will surely try to help you out.
So first of all I assume that you started the installation in a virtual environment, if  not then that's highly suggested because of obvious reasons as the extra dependencies make the core of operating system heavy.
So clone the repo and go to the augur directory.
create and activate your virtual environment in the new cloned repo 
switch to the dev branch
now run the following
make clean
make install 
For the option of using the existing directory, you have to provide with the absolute path of your Facade_worker that is in workers directory or augur.
Try doing that, it worked for me and I hope it works for you as well.
Also, did you follow the instructions and create the psql database with given name, user and password?
Also, it'll be better if you could provide us with your logs/backend.log file, that'll be helpful.

**Comment by NodiraIbrogimova** [comment] 2020-03-18 05:21
> So first of all I assume that you started the installation in a virtual environment, if not then that's highly suggested because of obvious reasons as the extra dependencies make the core of operating system heavy.

Yes, I followed instructions in [documentation](https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html).

> Also, did you follow the instructions and create the psql database with a given name, user and password?

I installed [Postgres.app](Also, did you follow the instructions and create the psql database with the given name, user and password?) and started running the server.
Now I have the following view in Postgres app:

<img width="637" alt="Screen Shot 2020-03-18 at 10 06 07 AM" src="https://user-images.githubusercontent.com/11291840/76927260-511d1b80-6900-11ea-9c9f-8515de50a5cc.png">

I don't have prior experience with practicing database, no experience in backend. I'm having problem with **Data collection** and **Backend** part of [Installation](https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html)

For example, how should I complete this:

- database name (AUGUR_DB_NAME)
- host (AUGUR_DB_HOST)
- user (AUGUR_DB_USER)
- password (AUGUR_DB_PASSWORD)
- port (AUGUR_DB_PORT)

Well..as long as you understood I'm in a mess :D

**Comment by NodiraIbrogimova** [comment] 2020-03-18 05:53
Here are `logs` outputs:
[backend-installation.log](https://github.com/chaoss/augur/files/4347203/backend-installation.log)
[frontend-installation.log](https://github.com/chaoss/augur/files/4347204/frontend-installation.log)
[workers-installation.log](https://github.com/chaoss/augur/files/4347205/workers-installation.log)

@Adarsh-NP @ccarterlandis

**Comment by NodiraIbrogimova** [comment] 2020-03-18 06:18
Here I provided detailed information about my steps in `augur` directory (in virtual environment) hoping to get help and give you guys more information to discover what's wrong in my installation process:

**1**. `make clean`
**2**. `make install`
**3**. Choosing option `2)` for
```
1) Would you like create the Augur database, user and schema LOCALLY?
2) Would you like to add the Augur schema to an already created Postgres 10 or 11 database (local or remote)?
3) Would you like to connect to a database already configured with Augur's schema? 
```
**4**. 
```
Database: augur
Host: 
Port: 5433
User: augur
Password: [password]
```
**5**. Choosing option `2)` for
```
The Facade data collection worker needs to clone repositories to run its analysis.
Would you like to use an existing directory, or create a new one?
1) Create a new directory
2) Use an existing directory
```
**6**. Giving absolute path for continuing step in **5**

`/Users/**<..........>**/augur/workers/facade_worker`

**7**. Result after step _**6**_

<img width="981" alt="Screen Shot 2020-03-18 at 11 09 14 AM" src="https://user-images.githubusercontent.com/11291840/76930725-f9cf7900-6908-11ea-8b70-d1b4c3942556.png">

**8**. Choosing option `1)` for:
```
Would you like to load your database with some sample data provided by Augur?
1) Yes
2) No
```
 **9**. Result after step _**8**_ :
<img width="764" alt="Screen Shot 2020-03-18 at 11 12 35 AM" src="https://user-images.githubusercontent.com/11291840/76930913-65b1e180-6909-11ea-8fdb-52ee5c5310df.png">

**10**. Prompted augur after all of this (even though got some errors in prev. steps :D ) and got the errors:

<img width="922" alt="Screen Shot 2020-03-18 at 11 13 41 AM" src="https://user-images.githubusercontent.com/11291840/76931125-d3f6a400-6909-11ea-9047-165ca6ff65fe.png">
<img width="1056" alt="Screen Shot 2020-03-18 at 11 13 54 AM" src="https://user-images.githubusercontent.com/11291840/76931122-d35e0d80-6909-11ea-8676-16777c8543ce.png">
<img width="973" alt="Screen Shot 2020-03-18 at 11 14 05 AM" src="https://user-images.githubusercontent.com/11291840/76931111-cf31f000-6909-11ea-91d4-f98364cc79f4.png">

**Comment by Adarsh-NP** [comment] 2020-03-18 06:22
Port is 5432, I don't know if 5433 works
Also, what about the host? Did you leave it blank?

**Comment by NodiraIbrogimova** [comment] 2020-03-18 06:25
Yes. I left it blank.

```
Database: augur
Host: 
Port: 5433
User: augur
Password: [password]
```

**Comment by NodiraIbrogimova** [comment] 2020-03-18 06:27
Couldn't connect to port 5432 from Postgres app, it's throwing popup message saying the port is busy. That's why tried port 5433 in installation process to prevent similar error 🙈

**Comment by NodiraIbrogimova** [comment] 2020-03-18 06:30
After `make clean`, tried with port `5432` now. It's throwing the same errors above (for all steps).

**Comment by ccarterlandis** [comment] 2020-03-18 21:45
Hi @NodiraIbrogimova, sorry I have not been as responsive these past few days. Let me try to clarify a few things.
1. You are correct in choosing option 2 (DB without the schema). With regards to credentials, since your database is running locally, your `host` should be `localhost`. Similarly, unless you have changed PostgreSQL's default port, your port should be `5432`; you can check your configuration by under the "Server settings" dialog box when using `Postgres.app`. When you enter the correct credentials, the script should create the `augur` user you, so that error should go away. 
2. We recommend using a dedicated folder that lives outside the `augur/` repository for your Facade data collection. This is so that the files do not get accidentally checked into Git, and if you need to reset all your data collection progress, you'll need to remove all the clones made by Facade; this is easier to do in its own folder IMO, since you don't have to worry about accidentally deleting the code for the `facade_worker`.
3. I'm not sure if loading the sample data still works, as we have actually switched to using Docker to distribute a sample dataset that we also use for testing purposes.

I would also like to extend my sincere apologies for the difficult you've been experiencing. Myself and the rest of the Augur team have been working very diligently to make a great many enhancements to our system. However, I have not been doing things properly and updating the documentation as I go, and have instead let it fall very far out of date for far too long. As a fellow programmer I wholeheartedly understand the aggravation that comes with missing, incorrect, or otherwise badly written documentation. I do hope you can forgive me for this.

In the coming days, however, @CMPerniciaro I will be opening a PR into `dev`

**Comment by ccarterlandis** [comment] 2020-03-18 21:50
I closed this on accident while trying to type out my above comment. I will keep it open until we are able to get you up and running as well @NodiraIbrogimova.

**Comment by NodiraIbrogimova** [comment] 2020-03-19 05:18
@ccarterlandis thank you so much for a detailed answer! :D 🎉At night I was able to fix the problem with the server. But, I got an error when I run `augur run`. After your comment I think it might be because of the installation with sample data from augur. 

> I'm not sure if loading the sample data still works, as we have actually switched to using Docker to distribute a sample dataset that we also use for testing purposes.

One question here is, does the sentence above mean I've better choose `No` for the option below?

```
Would you like to load your database with some sample data provided by Augur?
1) Yes
2) No
```

And if I got you right

> We recommend using a dedicated folder that lives outside the augur/ repository for your Facade data collection.  

means to use absolute path `/Users/<some folders here>/augur/workers/facade_worker` for facade_worker which is located in root augur folder? :D

**Comment by NodiraIbrogimova** [comment] 2020-03-19 05:29
Yaaaaaay! It worked! 🎉🎉🎉 Thank you, guys! @ccarterlandis @Adarsh-NP

**Comment by ccarterlandis** [comment] 2020-03-19 05:33
> One question here is, does the sentence above mean I've better choose No for the option below?
Yes, the correct option would be no. 

If you're familiar with Docker, and want to try the test database out, you can use the following command to run the container:
```
docker run -d -p 5434:5432 --name augur_test_database augurlabs/augur:test_data
```

You'll then need to change the `Database` section of your `augur.config.json` to:
```
    "Database": {
        "connection_string": "sqlite:///:memory:",
        "name": "test_data",
        "host": "localhost",
        "key": "your_github_access_token_here",
        "password": "augur",
        "port": 5434,
        "schema": "augur_data",
        "user": "augur"
    }
```
You could change the port from `5434` if you want, I just use it because it's close to the default PostgreSQL port.

> ..means to use absolute path /Users/<some folders here>/augur/workers/facade_worker

I would recommend explicitly _not_ using this path. For reference, I use `/Users/carter/projects/work/repos/` as my repo directory, and my augur installation lives at `/Users/carter/projects/work/augur/facade_worker/`. That way when the `facade_worker` clones the Git repositories to your machine, it doesn't clone into Augur's source code. If it did that things would get pretty messy pretty fast, since you'd be putting a Git repo inside a Git repo.

I'm glad you were able to get it working! 🎉

**Comment by Adarsh-NP** [comment] 2020-03-19 05:50
Ok, so I loaded the data. What should I do now because in the documentation
it was mentioned that we should load the data. 😅😅

**Comment by NodiraIbrogimova** [comment] 2020-03-19 05:54
Before you close the issue, I would like to share the steps I took during installation here in case someone else faces the same difficulty like I had. As my issue is related to this `issue`, @ccarterlandis can I post it here as a comment, please?

**Comment by Adarsh-NP** [comment] 2020-03-19 05:57
I feel that's a good thing to do considering we ran into the same issue.
Good thinking, but it would be better if we document it and attach it in
the documentation in a separate link maybe called as issues while
installation.
Will help a lot of people. What say Carter?

**Comment by ccarterlandis** [comment] 2020-03-19 06:04
@Adarsh-NP That is no problem. It's just a different dataset :) If you are doing development you will need to use the Docker image for testing, and if you want I can send you a link to first version of the documentation on how to set that up after I publish it.

@NodiraIbrogimova (and @Adarsh-NP) please feel free to share any feedback, notes or steps you have from your experience installing Augur. It'll really help me make our documentation a lot better to know where the specific pain points are from people who aren't used to all the pain points like I am 😂 

I will actually go ahead and open draft PR from our documentation branch into `dev`. That way you can compare your feedback to what I've already got written of the new instructions (spoiler: it's not a whole lot at the moment), and we can capture all the discussion around the new docs in a central location. 😁

**Comment by NodiraIbrogimova** [comment] 2020-03-19 06:05
@ccarterlandis said they are doing some changes in documentation. I'm afraid there might be some mess if they are making changes in the `installation` part as well.

If the changes we do don't conflict with the ones you guys (@ccarterlandis and @CMPerniciaro)are doing, I'm would be happy to contribute in [this](https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html#installing-augur) so people could directly see the changes from there. Otherwise, for the time being I can post it here in the comment and you could review and make some changes (maybe before we add them to documentation).

P.S. I thought it was a bad internet connection at the beginning, but it seems some links in the documentation are not working.

**Comment by NodiraIbrogimova** [comment] 2020-03-19 06:08
@ccarterlandis do we have some chat in slack or another platform? It would be great to have one for discussion (in case we don't have). I checked one link for slack somewhere in the description, but I couldn't open it.

**Comment by Adarsh-NP** [comment] 2020-03-19 06:11
@NodiraIbrogimova, yeah some links in the documentation are broken actually and our mentors are up on that.
For the time being lets create a document together on the installation issues we faced using google docs,  what say? Or commenting here would also help.

**Comment by Adarsh-NP** [comment] 2020-03-19 06:17
> @Adarsh-NP That is no problem. It's just a different dataset :) If you are doing development you will need to use the Docker image for testing, and if you want I can send you a link to first version of the documentation on how to set that up after I publish it.
> Yeah if possible, that would be helpful,  although I have no experience with docker yet.
But for the time being, what to do as of now, like since I've loaded the data and you said about the possibility of a .git file in .git (I've run into those errors while working for some of my personal projects XD) so what about writing the code for interaction with gitlab api.

**Comment by NodiraIbrogimova** [comment] 2020-03-19 06:17
Great, how about moving to `google docs` for working on documentation? We could see changes by each other and discuss commenting. It's better to move this discussion to a different place, IMO.
By the way, can you share your e-mail, please? Mine is:
`nodira.ibrogimova@gmail.com`

**Comment by Adarsh-NP** [comment] 2020-03-19 06:22
Yeah, even I feel so hence I mentioned it.
My mail is:
f20180806@goa.bits-pilani.ac.in

**Comment by ccarterlandis** [comment] 2020-03-19 06:22
@Adarsh-NP @NodiraIbrogimova I've gone ahead an opened a PR with what I've currently got written, but I think starting with Google Docs is a really great idea. It would be easier to consolidate your notes there, since it's all in real-time. If you like, I can also share a link to the document you create in the PR, and we can all work together there. Up to you 😁

**Comment by Adarsh-NP** [comment] 2020-03-19 06:23
Sure, we'll share the link.

**Comment by NodiraIbrogimova** [comment] 2020-03-19 06:23
@ccarterlandis yes :D

**Comment by ccarterlandis** [comment] 2020-03-19 06:24
I will go ahead and close this issue, but feel to use this thread or #616 to continue the discussion. I am excited to see what you all come up with! 🚀

**Comment by ccarterlandis** [comment] 2020-03-19 06:25
I will also work on getting everything set up in our Slack channel 😉

**Comment by NodiraIbrogimova** [comment] 2020-03-19 06:27
@ccarterlandis can you share the channel link please?

**Comment by ccarterlandis** [comment] 2020-03-19 06:29
@NodiraIbrogimova I've got to double check our permissions and then set up our guest access correctly, which I'll do in the morning (it's 1:30am where I am). I will post it in the main GSoC thread, and ping both you and @Adarsh-NP when I do so :)

**Comment by ArcD7** [comment] 2020-03-19 14:17
Hey @Adarsh-NP @ccarterlandis @NodiraIbrogimova . I hope you are doing well.
I followed your instructions for installation but when i try  `make install` on the dev branch i get this error 
![Screenshot from 2020-03-19 19-33-39](https://user-images.githubusercontent.com/46811622/77076748-4060c880-6a1a-11ea-810b-d1bdc386cadf.png)
But, when I try it  without changing the branch I get no error.

**Comment by NodiraIbrogimova** [comment] 2020-03-19 15:38
Hello @ArcD7! Can you share your backend.logs file, please?
You can find the file in `logs/backend.logs` of the `augur` root directory.

**Comment by ArcD7** [comment] 2020-03-19 16:32
Here you go!
[backend-installation.log](https://github.com/chaoss/augur/files/4355731/backend-installation.log)

**Comment by NodiraIbrogimova** [comment] 2020-03-19 16:39
Can you please let me know about these:
1. Did you `make install` in a virtual environment? (from log file seems yes)
2. What OS are you using?

Did you try running (after you created and activated virtual environment) `make clean` and then `make install`?

**Comment by ArcD7** [comment] 2020-03-19 16:41
1. Yes, I am using a virtual environment.
2. Its Linux Mint 

Yes, I did try `make clean`

**Comment by ccarterlandis** [comment] 2020-03-19 16:45
Hey @ArcD7, I think I can help. I've seen that `psutils` error before; can you try running `pip install wheel` in your virtual environment and then running the install process again? If that doesn't work you could also try installing the `python3-dev` tools. I'm fairly certain there is something wrong with the `psutils` library release, as I've run into other weird build errors with it before. Let me know how it goes!

**Comment by ArcD7** [comment] 2020-03-19 18:25
Thanks @ccarterlandis `installing python3-dev` did remove that error. But, after completing the build process this issue occurred. 
![Screenshot from 2020-03-19 23-49-44](https://user-images.githubusercontent.com/46811622/77101118-c857ca00-6a3c-11ea-89c7-bd35fed58928.png)
Also uploading the `backend installation logs`.
[backend-installation.log](https://github.com/chaoss/augur/files/4356325/backend-installation.log)
[frontend-installation.log](https://github.com/chaoss/augur/files/4356326/frontend-installation.log)
[workers-installation.log](https://github.com/chaoss/augur/files/4356327/workers-installation.log)
Really appreciate your help. Thanks! @ccarterlandis @NodiraIbrogimova

**Comment by ccarterlandis** [comment] 2020-03-19 18:37
@ArcD7 glad that fixed the problem. I'll make sure to add a note about that to the installation docs in case it happens to others.

I think there is more of that error message that is not in the screenshot, if you scroll down and copy from the very bottom it should displayed a specific exception name and location - looks to be somewhere in the housekeeper from what I can tell, but I can't be sure without the rest of the log. Additionally, how did you configure your database instance?

**Comment by ArcD7** [comment] 2020-03-20 11:31
Sorry, for the SS didn't notice that it wasn't complete. Here is the complete SS.
![Screenshot from 2020-03-20 16-48-25](https://user-images.githubusercontent.com/46811622/77159410-52e70a80-6acb-11ea-9918-5a0096cfd5ea.png)

For the Database, steps I followed were:

1. For downloading Postgresql, i used : `sudo apt-get install postgresql`
2. Then, I created a new database **augur** : `sudo su - postgres -c "createdb <name>`
3. Created a new role: `sudo su - postgres -c "createuser <name>"`
4. Granted all privileges to db
`sudo -u postgres psql`
`grant all privileges on database <dbname> to <username>`

Rest all procedures were followed the same way as @NodiraIbrogimova did!

**Comment by Adarsh-NP** [comment] 2020-03-20 13:53
Getting this new set of errors, @ccarterlandis  kindly suggest what could be done
![gyperror](https://user-images.githubusercontent.com/54997561/77169337-54bac900-6adf-11ea-91a0-304be4ee8fd5.png)
![builderror](https://user-images.githubusercontent.com/54997561/77169355-5a181380-6adf-11ea-9061-5fa0c87cd1f2.png)
That was bit foolish of me to redo everything to make sure no errors are generated, and now I can't regret it anymore.
Kindly help.
Here's the log file the screenshot asks to look for

[npm_logs.txt](https://github.com/chaoss/augur/files/4359884/npm_logs.txt)
I am sorry for troubling you but just wanted to be sure that everythings working alright and ran into it.
Thanks in advance

**Comment by Adarsh-NP** [comment] 2020-03-20 15:27
I am able to run make dev but it's just that augur run is not running.

**Comment by NodiraIbrogimova** [comment] 2020-03-20 16:09
@Adarsh-NP I got augur.json.config error once and command `augur configure generate` in `augur` - project root directory worked for me. Can you please try this one as well?

**Comment by ccarterlandis** [comment] 2020-03-22 21:59
@ArcD7 I think something went wrong during your schema installation process. If you don't mind, can you share the `Database` section of your `augur.config.json` (if you're running it locally that is, I would never ask you to share credentials to hosted database online 😂). If you're your credentials in there are correct, could you try running `augur db create-schema` from the root Augur directory? That script creates the schema, if it runs correctly it should create that `worker_job` table that you seem to be missing.

**Comment by ArcD7** [comment] 2020-03-23 19:08
@ccarterlandis  I think there is something wrong with the database, but I don't know what.
Here is the `augur.config.json` file:
[augur.config.txt](https://github.com/chaoss/augur/files/4371417/augur.config.txt)

> Converted to txt as json is not supported.

I then tried that command it didn't work, so I suppose the problem is with the psql setup.

**Comment by ccarterlandis** [comment] 2020-03-24 00:18
Can you be more descriptive about the command didn't work and provide error logs/screenshots please? I can't help you if I don't know what happened. I am not sure what you mean by the 'psql setup' either, do you mean how the database itself was created? Or something else?

**Comment by Adarsh-NP** [comment] 2020-03-26 21:00
Update:
So finally the commands worked for us..Thanks to @ccarterlandis for addressing our problems and @NodiraIbrogimova for working with me on the documentation and figuring out the errors.

**Comment by ccarterlandis** [comment] 2020-03-27 15:27
@ArcD7 were you able to get everything sorted out? I'm going to close this issue but feel free to open another if you are still experiencing issues.

**Closed by ccarterlandis** 2020-03-27 15:27 UTC
Labels: GSoC 2020, installation
