### ISSUE TITLE
augur run throws error: 

### ISSUE THREAD

**Issue by Adarsh-NP** [chaoss/augur#600] opened 2020-03-11 19:55 UTC
**Describe the bug:**

**To Reproduce:**

**Expected behavior:**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS v10.14.1]
 - Browser: [e.g. Chrome v64.5.13 or Safari v12.0.1]

**Additional context**

**Comment by ccarterlandis** [comment] 2020-03-12 00:26
I'm assuming this a duplicate of #601, but please reopen if it's not!

**Comment by ccarterlandis** [comment] 2020-03-19 15:15
Not sure how I reopened this yesterday. Whoops 😁

**Closed** 2020-03-19 15:15 UTC
