### ISSUE TITLE
SBOM Button not Working

### ISSUE THREAD

**Issue by germonprez** [chaoss/augur#416] opened 2019-10-14 14:13 UTC
**Describe the bug:**
SBOM is not producing SPDX

**To Reproduce:**
http://science.osshealth.io/repo/Senaite/senaite.core/risk

**Expected behavior:**
When I click the sbom link, I suspect to see an option to download an SPDX

**Screenshots**
http://science.osshealth.io/repo/Senaite/senaite.core/risk

**Desktop (please complete the following information):**
Mac/Firefox

**Additional context**
@Nebrethar

**Comment by sgoggins** [comment] 2019-10-14 14:15
@Nebrethar : Can you let @gabe-heim and @michaelwoodruffdev know if this is an issue you are aware of, or if there is possibly a need to rerun the risk stuff, `augur-sbom` on this instance because the sbom functionality was developed after we deployed this instance?

**Comment by Nebrethar** [comment] 2019-10-18 18:51
@germonprez I cannot reproduce this issue. This is working for me on chrome and firefox. I think I need more context i.e. browser logs.

Please note that when you click the SBOM button, it pushes a download to your browser. There is no middle interaction.

**Comment by Nebrethar** [comment] 2019-10-31 14:32
**A Note** : the data for SPDX documents is being repopulated on the time of this post. The SPDX dpcument download and license coverage will not be available for another day or so. I'll ask you to try again when it is finished

**Comment by Nebrethar** [comment] 2019-11-01 18:13
I found a compatibility issue where the download button was only working in certain browsers. It is fixed in #457

**Comment by Nebrethar** [comment] 2019-11-13 19:48
augur.osshealth.io reflects the download changes now. 
@germonprez please reopen if you still have this issue. It is working on all browsers now.

However, I will open a new issue to fix the TypeScript loading of the JSON document. Right now it is on a single line.

**Closed** 2019-11-13 19:48 UTC
Labels: bug, frontend
