### ISSUE TITLE
Git REPO Performance Improvement Guarantee

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#178] opened 2018-09-21 02:19 UTC
**Describe the bug**
We are using the analysis tables in the Facade schema to generate those pages. Turns our the "cache" tables have the same data in summary form, and if we query those instead we are going to get much better performance (thanks, @brianwarner)

**To Reproduce**
It just works faster against the different tables.

**Comment by ccarterlandis** [comment] 2018-10-25 20:19
Semi-duplicate of [this](https://github.com/chaoss/augur/issues/183) issue. That one has been resolved, so I'll close this one.

**Closed by ccarterlandis** 2018-10-25 20:19 UTC
Labels: API, critical, duplicate, enhancement
