### ISSUE TITLE
Top Graph on Insights not Rendering Well 

### ISSUE THREAD

**Issue by germonprez** [chaoss/augur#417] opened 2019-10-14 14:15 UTC
**Describe the bug:**
Top Graph on Insights not Rendering Well 

**To Reproduce:**
http://science.osshealth.io/inspect_insight/Samvera/https:%2F%2Fgithub.com%2Fsamvera%2Fmaintenance.git/issues-new/

**Expected behavior:**
The graph is just rendering funny

**Screenshots**
<img width="828" alt="Screen Shot 2019-10-14 at 9 13 37 AM" src="https://user-images.githubusercontent.com/656208/66757987-fb30dd00-ee62-11e9-8451-0fe4fe0f9de8.png">

**Desktop (please complete the following information):**
Mac/Firefox 

**Additional context**
@sgoggins and @gabe-heim

**Comment by sgoggins** [comment] 2019-10-14 14:21
@gabe-heim : I confirmed that this is an issue on both Chrome and Firefox.

**Comment by sgoggins** [comment] 2019-10-23 23:43
This is in progress and will be released soon.

**Comment by Nebrethar** [comment] 2019-11-18 16:33
Issue related to #401 Also, @sgoggins has this been fixed lately?

**Comment by ccarterlandis** [comment] 2020-02-28 16:18
This graph looks like it no longer renders in this wonky format, at least on augur.osshealth.io

**Closed by ccarterlandis** 2020-02-28 16:18 UTC
Labels: bug, deployed version, frontend
