### ISSUE TITLE
Running "augur" command File Not Found in webpage

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#195] opened 2018-11-20 16:12 UTC
**Describe the bug**
I cannot seem to get augur working with the "augur" command from a dev install. It states that It is listening on 0.0.0.0:5000 (from the config file) but I get a 404 in the webpage for it.

**To Reproduce**
1. Run "augur"
3. Go to config-based URL (0.0.0.0:5000 for me)
4. See 404

**Expected behavior**
I expected to be on the augur webpage

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/48786642-e11b6880-ecac-11e8-883e-5cbb1567ace2.png)
![image](https://user-images.githubusercontent.com/34951354/48786475-91d53800-ecac-11e8-87b4-8f41f68e2fb1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
- Branch: Dev

**Additional context**
I am able to connect at localhost:3333 when I run make-dev. My augur works fine then.

**Comment by ccarterlandis** [comment] 2018-11-21 01:03
This issue was caused by the fact that in fact, there was no URL for `0.0.0.0:5000/`. All API routes contain the current API version (currently `/api/unstable/`), so I simply added a redirect from `0.0.0.0:5000/` to `0.0.0.0:5000/api/unstable/`. This is the de facto "default" page for the API, as it just shows the API is reachable by displaying a short status message.

Fixed in `dev` in [this](https://github.com/chaoss/augur/commit/162f274339a90008ea823534c345cff59419c65b) commit.

**Closed by ccarterlandis** 2018-11-21 01:03 UTC
