### ISSUE TITLE
Error occurs when installing Augur's frontend  dependencies 

### ISSUE THREAD

**Issue by tianyichow** [chaoss/augur#631] opened 2020-03-25 11:02 UTC
**Describe the bug:**
<img width="1056" alt="1" src="https://user-images.githubusercontent.com/42535236/77533441-d345ab00-6ed1-11ea-9b2c-ac617394eb12.png">
<img width="1060" alt="2" src="https://user-images.githubusercontent.com/42535236/77533545-09832a80-6ed2-11ea-943c-c5c2d50e7912.png">

**To Reproduce:**
1. make install
2. Would you like to install Augur's frontend dependencies? ( yes)

**Expected behavior:**
 Backend and worker dependencies  are successfully installed on my machine. But errors occur when I choose to install frontend depenedncies. So after the installation, I run "augur run" command, the backend server works well：

<img width="1054" alt="3" src="https://user-images.githubusercontent.com/42535236/77533562-11db6580-6ed2-11ea-88e1-a67e94868c0f.png">
But I got a blank web page on my browser. 

![image](https://user-images.githubusercontent.com/42535236/77533766-6aaafe00-6ed2-11ea-92bc-5ddae82e8a5f.png)

I didn't find frontend-installation.log in *augur/log*. 
**Desktop (please complete the following information):**
 - OS: CentOS 7.7.1908

**Comment by tianyichow** [comment] 2020-03-25 12:09
I redo the building procedure on my Macbook Pro. I saw the same issue.
I sincerely ask for help 😂
Log files ：
[backend-installation.log](https://github.com/chaoss/augur/files/4380727/backend-installation.log)
[frontend-installation.log](https://github.com/chaoss/augur/files/4380728/frontend-installation.log)
[workers-installation.log](https://github.com/chaoss/augur/files/4380729/workers-installation.log)
@ccarterlandis
@sgoggins
@gabe-heim

**Comment by ccarterlandis** [comment] 2020-03-25 16:31
Hi @tianyichow, sorry you've been having issues. I'll be glad to work with you to get everything figured out.

### Frontend
I fully recognize that this is weird and unexpected behavior, but those frontend error messages are not true "errors". Having seen this issue all the time, I know that the last bit of your error message should look like this: 
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.11 (node_modules/canvas-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

You'll notice that the only places there are errors in the installation are after these two lines:
> canvas-prebuilt@1.6.11 install ...
> canvas@1.6.13 install ...

For whatever reason, one of our dependencies (I believe it's `vue-vega`) uses an old version of `canvas` and it does not work. Regardless, it's a completely optional dependency, so your frontend installation should actually work okay, provided there aren't further errors not shown here. 

Again, so sorry this happens, I know how weird it is. I am not a Javascript developer and I'm not familiar enough with `npm` to diagnose further. A fix for this would be nice to have, but it's not mission critical, so we have not gotten around to it.

### Backend
It actually looks like your backend is functioning correctly; the issue is simply that `http://localhost:5000` is not a route on the server. Go to `http://localhost:5000/api/unstable/` and you should see an `OK` message (assuming your port is 5000) - try that and see what happens, as that is what I use for the "healthcheck" route.

Hope this helps!

**Comment by tianyichow** [comment] 2020-03-25 17:28
Thanks a lot for your help @ ccarterlandis!

### Frontend

I checked the error info and it is exactly what you say. 😂

If this is caused by opitional dependency, the frontend should work well on the browser. But I can't get the right visual web page.  I suppose that the right thing is:

![image](https://user-images.githubusercontent.com/42535236/77566655-ef147580-6f00-11ea-9078-d0a68cb3cf7e.png)
(This picture is from other issues)

Is there any way( a test route address, etc) to check whether the frontend function works well?

### Backend

Yes, I  got a `ok` message on `http://localhost:5000/api/unstable/` and all functions seems to work well. I can find the example data in the `augur` database.  (The sample data structure is quite similar with GHTorrent. Currently I am doing some research on mining software repositories.) It seems that it dosen't hinder me from analyze the data with ML techniques with out the frontend. So I can go ahead to do the micro tasks of CSoC.😊

**Comment by ccarterlandis** [comment] 2020-03-25 17:34
@tianyichow glad I was able to help you solve the issue. The frontend server is on `http://localhost:8080` by default, can you see if that works? `augur run` does not control the frontend server`, if you want to spin the frontend up then you have 2 options:

1. Run `make dev` in the root `augur/` directory to start BOTH in frontend and the backend as background processes
2. Keep `augur run` going in one terminal, and run `npm run serve` in `augur/frontend` directory in another terminal

Let me know how it goes! I'll keep the issue open until we can verify your installation is working correctly.

**Comment by ccarterlandis** [comment] 2020-03-25 17:37
For what it's worth, the test data packaged with the repository is several months out of date, and we are removing it from the installation process in our upcoming release in favor of using our new Docker database with richer and updated sample data (that is also used as our testing environment). I am actually working on updating the test data right now, so if you like I can share instructions on how to use it when I am done 😊

**Comment by tianyichow** [comment] 2020-03-25 18:16
🍻cool！！！！@ccarterlandis, it works fine. Thanks for your help.
![image](https://user-images.githubusercontent.com/42535236/77569607-6946f900-6f05-11ea-91c5-60737cddc7e0.png)

I am quite interested in the new richer sample data. I would like to try it in the upcoming release and help to improve it. 😊 Now  I am working on the socail collaboration network analysis in open source community based on data from GitHub. My lab published the 2019 China Open Source Digital Annual Report whith the analysis of 546 million event records generated in 2019 on GitHub. I believe that Augur would help me a lot in my further research! I will get fammilar with it as soon as possible and seek for contribution opportunities based on my research during my postgraduate works.

Have a good day!😸

**Comment by ccarterlandis** [comment] 2020-03-25 18:43
Wow, that sounds really interesting!! Is that report available online anywhere? Sounds like a pretty cool dataset. If you're interested in what we do, we are part of the Linux Foundation's [CHAOSS](https://chaoss.community) project, which is focused on Community Health and Analysis for Open Source Software (hence the name). We work with open source stakeholders from all over the world in a variety of projects to identify and implement metrics that are valuable to people who are running those projects, or are just interested in them. You can find out more info on the website, or I'd be happy to answer any questions you might have.

I'm glad it's all working correctly now! I hope you have a good day too, and stay safe! 🚀

**Closed by ccarterlandis** 2020-03-25 18:43 UTC

**Comment by tianyichow** [comment] 2020-03-26 09:51
@ccarterlandis sorry for response so late. 😂
The report and a analysis tool are available in our GitHub:https://github.com/X-lab2017/github-analysis-report-2019. But there are just Chinese version of it. However, I has working on a demo paper based on this work for VLDB conference 2020. We provide a pre-processed [dataset](http://cdn.opensource-service.cn/github-analysis-report-2019/data.json.gz) which is derived from GH Archive project. You can run the analysis tool on this dataset to get the ranking list of active level of all projects on GItHub in 2019.  We also give some visualizations of some projects to get insight of the collaboration patterns. And I believe that if we can utilize data from all aspects from open source communities with proper methods, it  will helps a lot to improve sustainability of softwares. So now my lab in East China Normal University is working on this. Here are some results of the report:
Top 20 Chinese open source project:
![image](https://user-images.githubusercontent.com/42535236/77632495-0a2ac800-6f89-11ea-8ae4-2d8ce2702671.png)
Collaboration networks during the development of projects (screenshot from my paper):
![image](https://user-images.githubusercontent.com/42535236/77632691-5413ae00-6f89-11ea-8ada-b623da996a84.png)

One of our mentor, William Jiang, who is a member of ASF and an expert in open source recommended the CHAOSS project to us. He encouraged us to get fammilar with Chaoss and try to combine our own research with it. I am both interested in open source sustainability and Data Science (  I am a postgraduate student in Data Science). Some works I had done before are trying  do some evaluation model and network analysis for open source communities. This project is really amazing and exactly in line with what I want to do.  Before I know this project, we just do some case studies of OSS  at school.
