### ISSUE TITLE
Augur Installation

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/augur#413] opened 2019-10-11 22:11 UTC
All the links of front end dependencies are broken.
Frontend
Vue.js
vue-cli
npm

**Comment by GeorgLink** [comment] 2019-10-11 22:30
We took notes as @andyl @vinodkahuja and @GeorgLink tried to go through the installation. We also recorded the session in the CHAOSS Zoom channel. Maybe @germonprez can share the link.

I suggest someone from the augur team look through the notes and watch the video to see what roadblocks we faced, what didn't make sense, and from all that to make improvements to the installation instructions.

Here are the notes we jotted down:

*   Local Desktop Ubuntu 18.04
*   Postgres installed
*   Python 2 and 3 installed
*   $ git clone https://github.com/chaoss/augur.git
*   $ cd augur
*   $ git checkout osd-2019
*   Check python, pip, and postges version
*   Q? Why install through the osd-2019 branch and not master?
*   $ python3 -m venv ~/.virtualenvs/augur_env
*   $ ls ~/.virtualenvs/augur_env
*   change the python symlink to python3.6 (was python 2.7 before)
    *   cd /usr/bin
    *   sudo ln -s python3 python
*   Q? The make install script asks yes/no questions but requires numbers to be typed.
*   The virtual environment was created, but the install instructions do not say how to switch into it.
*   $ source ~/.virtualenvs/augur_env/bin/activate
*   Q: what is “key” in the installation of postgres
*   skipped key
*   skipped GitHub API key
*   Q: Link to the Augur schema is not broken -- https://github.com/chaoss/augur/issues/412
*   The ./augur/persistence_schema instructions contain an old file name and do not provide instructions for how to import the files into Postgres
*   Manually created the database
    *   Start psql with "psql -U <youruser>"
    *   "CREATE DATABASE <YOURDB>"
    *   "\q" to exit
*   $ psql -U postgres testdb < 0-all.sql
*   Q: all links in README for “Frontend” are broken.

**Comment by ccarterlandis** [comment] 2019-10-11 23:46
I will watch the video ASAP, but in the meantime I hope I can answer some of your questions here. 


> Q? Why install through the osd-2019 branch and not master?

The `master` branch is not exactly ready for widespread use or distribution. We have been in a **very** rapid development mode and are working on a formal stabilization release. The instruction to use the `osd-2019` branch was intended to be used for the Open Source Day at Grace Hopper last week: the fact that had not been changed is a simple oversight. I understand that this probably had adverse affects on the rest of the installation: my apologies for the confusion.


> Q? The make install script asks yes/no questions but requires numbers to be typed.

This functionality is determined by my use of the `select` statement in `bash`. It automatically handles much of the logic for accepting user input for us in a very clean way, which is why I chose to use it. The prompt for the user's input should read 
```
Please type the number corresponding to your selection and then press the Enter/Return key.
Your choice: 
```
I understand you were on the `osd-2019` branch, which might not have this prompt; in that case I understand the confusion. If the prompt is not clear enough I can look into alternative options.


> The virtual environment was created, but the install instructions do not say how to switch into it.

Immediately after the virtual environment, you should see two lines that look like this: 
```
*** Your environment was installed to $HOME/.virtualenvs/augur_env/. Please activate and restart the installation using your shell's appropriate command. ***
*** For example, if you're using bash, run 'source $HOME/.virtualenvs/augur_env/bin/activate'. ***
```
These instructions detail how to activate the virtual environment. Please let me know if you did not see these instructions and I will pay extra attention to the video to see what might have happened.


> change the python symlink to python3.6 (was python 2.7 before)
    cd /usr/bin
    sudo ln -s python3 python

I'm not sure we should include this process in the installation instructions. I don't want to mess with a user's installation of python if we don't have to: so long as they have Python 3.6 or later installed, I think creating taht 


> Q: what is “key” in the installation of postgres?

This I am not sure about, @gabe-heim might have a better idea: I believe it is needed. We definitely need more documentation explaining what this part is my apologies for the confusion here. I have made a note to address this in our next release.


> skipped GitHub API key

Was this on purpose? This is necessary for Augur to work.


> Q: Link to the Augur schema is not broken -- #412

This has been on my radar, but I completely forgot about it - thank you for reminding me. I will make sure to fix it in the next release.


> The ./augur/persistence_schema instructions contain an old file name and do not provide instructions for how to import the files into Postgres

I believe those instructions are old; however, the installation script should take care of creating the database in most cases. Regardless, to cover the cases where it does not, I will update those instructions.


> Q: all links in README for “Frontend” are broken.
Thank you for bringing this to our attention, as I had no idea this was the case. I will make sure to fix it in the next release.

Thank you for your detailed feedback @GeorgLink @vinodkahuja! I understand it was not a smooth process, but we are in the middle of a major stability update and are in the process of getting a lot of changes deployed that will make the installation experience much better. 

I do wish myself or some other members of the Augur team could have been on the call to assist, as I'm not sure we are really ready for a "formal" installation test given that we are still in the middle of stabilizing the process. Regardless, your feedback is **_very_** helpful as for most of these bugs I had no idea they were happening, so I sincerely appreciate your dedication to documenting the process in order to help us. Your notes and your video will help us make sure the next release is as well-organized as possible.

I hope you understand our current state of affairs and I hope it does not negatively color your view of Augur. We are working very hard to make it as painless as possible! Thanks again!

**Comment by GeorgLink** [comment] 2019-10-12 00:06
> I hope you understand our current state of affairs and I hope it does not negatively color your view of Augur. We are working very hard to make it as painless as possible! Thanks again!

Yes of course. Thank you for all the work you already put into this. Thank you for the quick response.



> > Q? The make install script asks yes/no questions but requires numbers to be typed.
> 
> This functionality is determined by my use of the `select` statement in `bash`. It automatically handles much of the logic for accepting user input for us in a very clean way, which is why I chose to use it. The prompt for the user's input should read
> 
> ```
> Please type the number corresponding to your selection and then press the Enter/Return key.
> Your choice: 
> ```
> 
> I understand you were on the `osd-2019` branch, which might not have this prompt; in that case I understand the confusion. If the prompt is not clear enough I can look into alternative options.

It did say that.
The second prompt was very similar to the first and we repeatedly did not think that the script correctly accepted our answer. You'll see when you watch the video that we started the script multiple times.


> > The virtual environment was created, but the install instructions do not say how to switch into it.
> 
> Immediately after the virtual environment, you should see two lines that look like this:
> 
> ```
> *** Your environment was installed to $HOME/.virtualenvs/augur_env/. Please activate and restart the installation using your shell's appropriate command. ***
> *** For example, if you're using bash, run 'source $HOME/.virtualenvs/augur_env/bin/activate'. ***
> ```
> 
> These instructions detail how to activate the virtual environment. Please let me know if you did not see these instructions and I will pay extra attention to the video to see what might have happened.

I'm talking about the instruction in the README. They only say to create the virtual environment. We did. But the README did not say to activate the virtual environment, and so the install script complained.



> > change the python symlink to python3.6 (was python 2.7 before)
> > cd /usr/bin
> > sudo ln -s python3 python
> 
> I'm not sure we should include this process in the installation instructions. I don't want to mess with a user's installation of python if we don't have to: so long as they have Python 3.6 or later installed, I think creating a virtual environment (which should automatically link the `python` alias to Python 3.6, given it was created correctly) should suffice in most cases.

Yes, it should not be part of the instructions. We simply documented what we did.



> > skipped GitHub API key
> 
> Was this on purpose? This is necessary for Augur to work.

We just wanted to get through the installation. We didn't have the API key at hand and were planning to add it later.



> > The ./augur/persistence_schema instructions contain an old file name and do not provide instructions for how to import the files into Postgres
> 
> I believe those instructions are old; however, the installation script should take care of creating the database in most cases. Regardless, to cover the cases where it does not, I will update those instructions.

The README says that we need to do this as a prerequisite for `make install`. It would be great if the instructions in the README were clarified.

**Comment by ccarterlandis** [comment] 2019-10-12 00:09
@GeorgLink sounds good, it seems a lot of the confusion was the `README` and the installation script being out of sync with each other...I will absolutely make sure they have parity when we release to avoid most of these "conflicting instruction" errors. Truth be told I didn't even think to update the `README` when I was updating the installation script. 😅 I will definitely watch the video later this weekend!

**Comment by andyl** [comment] 2019-10-12 00:42
@ccarterlandis thanks for your extensive reply

> I hope you understand our current state of affairs and I hope it does not negatively color your view of Augur. We are working very hard to make it as painless as possible!

I'm in this for the long haul & understand how it is working with new software.  I very much like your the energy and dedication.  Here are some general points of feedback...

Simplify:
- the DB schema is large and hard to grok
- could it be cut way back?  
- could JSON fields be used to handle edge-cases?
- would a reduced scope help to improve quality and reliability?

Decouple:
- the main components (DbSchema, Workers, Runner, API, UI) are interwoven
- could they be separated into standalone components?
- could the workers or job runner interoperate with Perceval? (mix and match)

Market Research:
- who are the target users?
- which metrics are *most* important for the key users?
- focus on narrow set of use cases might be a path to simplification

Package:
- could the components be delivered in Docker containers (for end-users)?
- could you reduce the number of host architectures (for developers)?

Alternate Delivery Models:
- right now the only developer option is local installation
- could you give developers access to read-only database instance? 
- eliminate the need for local installation could simplify things a great deal

Interoperate:
- many Augur functions are duplicate code built for Grimoire
- is there opportunity to share components? (workers, job runners)

**Comment by germonprez** [comment] 2019-10-12 11:24
Here is the link: https://youtu.be/eingC53wdvg

**Comment by GeorgLink** [comment] 2019-10-13 13:36
Thanks Matt!

**Comment by sgoggins** [comment] 2019-10-13 14:36
@andyl A few responses; 
```
Simplify:

    the DB schema is large and hard to grok
    could it be cut way back?
    could JSON fields be used to handle edge-cases?
    would a reduced scope help to improve quality and reliability?
```
This is not really a question of simplification, but a question of where the work of making sense of the data will take place, and the value placed on cross-platform metric consistency architecturally traded off against speed of collection. 

When data is collected but not groked at that time, it has to be groked piece by piece in the implementation of metrics. Under these circumstances if one uses JSON collected "as is" from multiple sources, there cannot be a contract ensuring that a metric from one platform is equivalent to the same metric culled from a different platform. 

Its not a question of whether or not the domain is complex; it is. The question is where do we ask developers to deal with that complexity. 

Augur handles the complexity for you, and provides a contract ensuring consistency across platforms that is not possible with JSON focused collections. 

What we CAN do is build out the API endpoints so that the schema has a layer of indirection against it. 

```
Decouple:

    the main components (DbSchema, Workers, Runner, API, UI) are interwoven
    could they be separated into standalone components?
    could the workers or job runner interoperate with Perceval? (mix and match)
```
The workers are designed to feed the schema. There is no coupling between the API and the workers. 

Interacting with Perceval is something we welcome a pull request on, but perceval's contract is only to collect data, not to structure it, organize it or ensure cross platform consistency. That work is postponed to the panel construction phase in other parts of Grimoirelab. 

```
Market Research:

    who are the target users?
    which metrics are most important for the key users?
    focus on narrow set of use cases might be a path to simplification
```
We are focused on the community manager, and our advances recently in ease of installation make the kind of useful feedback provided by this session possible. Where we were six weeks ago would not have allowed a session like this to run without Augur developers in the call. 


```
Package:

    could the components be delivered in Docker containers (for end-users)?
    could you reduce the number of host architectures (for developers)?

````

Yes. That is on our roadmap. 

```
Alternate Delivery Models:

    right now the only developer option is local installation
    could you give developers access to read-only database instance?
    eliminate the need for local installation could simplify things a great deal
```
we do this through the API for a number of folks already. 

```
Interoperate:

    many Augur functions are duplicate code built for Grimoire
    is there opportunity to share components? (workers, job runners)
```

Here again, I think the difference between grimoire and augur is the architectural choice about when and where to ensure data consistency across platforms. I think the perceived simplicity of a bucket of JSON files dissipates as one goes beyond the first few implementations of metrics based on that bucket of JSON. An API and consistent relational schema is an architectural choice that we made so that the relationship between parts of the world, and decentralized source data for different kinds of data (issues, commits, mailing lists) is reconciled for the developer one time for all sources. Its a question of who does the work: The implementation developer or the platform. Augur takes more responsibility for data organization. 

Could Grimoire build panels off of our API's? I am not sure. My impression is that the panels are tightly coupled with the JSON structure.

**Comment by sgoggins** [comment] 2019-10-13 14:49
> Here is the link: https://youtu.be/eingC53wdvg

At 9:20 in the video Andy states that we are assuming that "python is python3, but for me it is python 2". If the instructions to create a virtual enviornment are followed, and the environment is activated, then this is moot. In a python3 virtualenv, "python" is "python3".  

The same instructions apply to grimoirelab as well. It is good python practice to use virtualenv's. to some extent we are 'over documenting' here to enable any newcomer with, or without, familiarity with Python to install augur.

**Comment by sgoggins** [comment] 2019-10-13 14:56
> Here is the link: https://youtu.be/eingC53wdvg

At 14:20 Georg and Andy realize the virtualenv needs to be activated. This is in the instructions after the creation of the virtualenv. This is also a fundamental practice for Python development. We are working to emphasize this process for people who are unfamiliar with working in Python in the setup instructions based on it being missed on this video.

**Comment by sgoggins** [comment] 2019-10-13 15:39
> Here is the link: https://youtu.be/eingC53wdvg

The issues related to `bdist_wheel` at 15:45 are a function of the `wheel` package not being installed. 

This is a common package, and we are going to change the way we recommend creating virtual enviornments. The `virtualenv` package installs essential python packages by default in new virtual environments, including `wheel`. 

`pip3 install virtualenv` or `pip install virtualenv`

`virtualenv --python=python3 augur_env` will remove this roadblock for people new to Python. 

```
sean@augurlabs:~$ virtualenv --python=python3 augur-env
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/sean/augur-env/bin/python3
Also creating executable in /home/sean/augur-env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
```

**Comment by sgoggins** [comment] 2019-10-13 15:42
> Here is the link: https://youtu.be/eingC53wdvg

At 17:30, @vinodkahuja is referencing Anaconda, which is from a previous version of the README file.  This instruction no longer exists. Augur does not use Anaconda by default anymore (and has not for six months).

**Comment by sgoggins** [comment] 2019-10-13 15:48
> Here is the link: https://youtu.be/eingC53wdvg

The prompting for a key at 21:00 is a defect in the installer. This is the GitHub API key, and we do prompt you for it again in the next step. We are changing the installer so that this key prompt is clearly labeled "Github API Key", and we only ask you for it once.

**Comment by sgoggins** [comment] 2019-10-14 14:36
> All the links of front end dependencies are broken.
> Frontend
> Vue.js
> vue-cli
> npm

@vinodkahuja : can you clarify what you mean. Are you saying that it does not compile the frontend on your computer? What is the OS? Do you have NPM installed?

**Comment by vinodkahuja** [comment] 2019-10-14 14:47
@sgoggins on the readme page when I follow the instructions to install front end dependencies, readme page provides me link to those dependencies installation. When I click any of the link I get an error message. That is where I raised this issue that all the provided links are broken.

**Comment by sgoggins** [comment] 2019-10-23 23:41
The points discussed in this issue are addressed in the latest release of augur.

**Closed by sgoggins** 2019-10-23 23:41 UTC
Labels: Learning Python, NDE, installation, question
