### ISSUE TITLE
Top Commiters API problem.

### ISSUE THREAD

**Issue by ilam56** [chaoss/augur#615] opened 2020-03-19 05:44 UTC
**Describe the bug:**
the "top-commiters" get request in the api doc http://augur.osshealth.io/api_docs/#api-Experimental-top_committers_repo doesn't seem to work for many repos. I think the repo-group version doesn't work right either. For some repos it will just give an internal server error and for others the number of commits don't seem to add up to the right number.

**To Reproduce:**
1. Go to http://czi2.osshealth.io:5153/api/unstable/repos/26732/top-committers
2. Go to http://czi2.osshealth.io:5153/api/unstable/repo-groups/252/top-committers
3. Go to http://czi2.osshealth.io:5153/api/unstable/repo-groups/201/top-committers

**Expected behavior:**
For the first and second link I get internal server errors despite the aggregate summary for those ids showing that they have commits. They shouldn't have resulted in internal errors. The third link is an example where the number of commits don't add up. Bases on the aggregate summary the Astral repo group has 43 commits but the top commiter + others only adds up to 3 commits

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1903(OS Build 18362.720)
 - Browser: Chome Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
I am a student of Goggins when I told him about this problem he said to submit an Issue, so here it is.

**Comment by ccarterlandis** [comment] 2020-03-22 03:43
Hi @ilam56, thanks for bringing this to our attention. I'll get started on a fix.

**Comment by pratikmishra356** [comment] 2020-03-27 16:22
@ccarterlandis I found that "top-commiters" metric endpoint were not mentioned in metrics/commits/routes.py .Instead it is mentioned in metrics/contributor/routes.py .This might be the cause of error.Can I work on this issue and resolve this??

**Comment by pratikmishra356** [comment] 2020-03-28 14:40
@ccarterlandis I think there might be some errors in the calculation part , thats why in the third link it is showing partial data.Currently none of the link is working.

**Comment by pratikmishra356** [comment] 2020-03-28 19:58
@ccarterlandis @ilam56 This issue occurs due to the following reason
 First and second link is showing internal errors because the "sql" queries not giving desired output, it returns None Type.
![Screen Shot 2020-03-29 at 1 09 27 AM](https://user-images.githubusercontent.com/43684300/77832244-9dffbe00-715a-11ea-8cfd-96d6d3c96bfd.png)
![Screen Shot 2020-03-29 at 1 10 15 AM](https://user-images.githubusercontent.com/43684300/77832247-a5bf6280-715a-11ea-9996-b0f8ccc5e4a8.png)

 Third link shows only 3 commits instead of 43 because it collects data from sql but fails to add commits properly.
I will soon raise PR fixing this

**Comment by sgoggins** [comment] 2020-04-03 22:40
@pratikmishra356 : I am curious about why several files unrelated to the the bug you note in the top-committers API are also changed?

**Comment by pratikmishra356** [comment] 2020-04-05 06:38
@sgoggins Sir , my target branch for pull request was dev but it was merged to GSoC branch.Due to this several unrelated files got changed.
I had made four commits (1,2 - fixed api issues ),(3 - added new notebook)(4 - Added new metrics).Same pull request were raised for all four commits.

**Comment by sgoggins** [comment] 2020-08-20 10:44
fixed.

**Closed by sgoggins** 2020-08-20 10:44 UTC
Labels: bug, metric
